galaxy_info:
  author: Jan Christian Grünhage <jan.christian@gruenhage.xyz>
  description: Install Sygnal (Matrix push gateway sever)

  license: AGPLv3

  min_ansible_version: 2.5

  platforms:
  - name: Debian
    versions:
    - 9
    - 10

  galaxy_tags: []

dependencies: []
