---
- name: create appservice group
  group:
    name: "matrix-appservices"
    state: present
    system: yes
  register: appservice_group

- name: create user
  user:
    name: synapse
    state: present
    groups: [ "matrix-appservices" ]
    append: yes
  register: synapse_user

- name: create directory
  file:
    path: "{{ matrix_synapse_base_path }}"
    state: directory
    owner: synapse
    group: synapse
    mode: 0750
