---
# defaults file for yggdrasil
yggdrasil_config_path: /etc/yggdrasil.conf
yggdrasil_config_listen_address: "[::]:61216"
yggdrasil_admin_listen_address: "unix:///var/run/yggdrasil.sock"
yggdrasil_extra_peers: {}
yggdrasil_ansible_peers: []
yggdrasil_multicast_interfaces:
  - regex: ".*"
    beacon: true
    listen: true
    port: 0
yggdrasil_limit_incoming_connections: true
yggdrasil_node_name: "{{ inventory_hostname }}"
yggdrasil_node_info_privacy: false
yggdrasil_node_info:
  name: "{{ yggdrasil_node_name }}"
  deployment: ansible
