stages:
  - build
  - publish

build:
  image: docker.io/alpine
  stage: build
  before_script:
    - apk add --no-cache ansible
  script:
    - ansible-galaxy collection build
  artifacts:
    paths:
      - famedly-matrix-*.tar.gz

publish:
  image: docker.io/alpine
  stage: publish
  before_script:
    - apk add --no-cache ansible
  script:
    - ansible-galaxy collection publish ./famedly-matrix-*.tar.gz --api-key ${ANSIBLE_GALAXY_API_TOKEN}
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
