---
- meta: noop
  vars: &sshd_config_args
    path: "{{ ssh_config_file }}"
    state: present
    validate: "sshd -Tf %s"
  tags: ['prepare', 'prepare-sshd']

- name: Disallow password authentication
  lineinfile:
    <<: *sshd_config_args
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Disallow challenge-response authentication
  lineinfile:
    <<: *sshd_config_args
    regexp: "^#?ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Allow pubkey authentication
  lineinfile:
    <<: *sshd_config_args
    regexp: "^#?PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    firstmatch: yes
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Disallow root login
  lineinfile:
    <<: *sshd_config_args
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Do not allow sessions to idle longer than 5 minutes
  lineinfile:
    <<: *sshd_config_args
    regexp: "^#?ClientAliveInterval"
    line: "ClientAliveInterval 300"
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Only allow SSHv2
  lineinfile:
    <<: *sshd_config_args
    regexp: "^#?Protocol"
    line: "Protocol 2"
    insertafter: &cipher_after "^# Ciphers and keying"
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Disallow X11-Forwarding
  lineinfile:
    <<: *sshd_config_args
    regexp: "^#?X11Forwarding"
    line: "X11Forwarding no"
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Disallow Agent Forwarding
  lineinfile:
    <<: *sshd_config_args
    regexp: "^#?AllowAgentForwarding"
    line: "AllowAgentForwarding no"
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Disallow TCP Forwarding
  lineinfile:
    <<: *sshd_config_args
    regexp: "^#?AllowTcpForwarding"
    line: "AllowTcpForwarding no"
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Only allow reasonably secure KeyExAlgorithms
  lineinfile:
    <<: *sshd_config_args
    regexp: '^#?KexAlgorithms'
    line: "KexAlgorithms {{ ssh_preset.allowed_kexalgos|join(',') }}"
    insertafter: *cipher_after
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Only allow reasonably secure ciphers
  lineinfile:
    <<: *sshd_config_args
    regexp: '^#?Ciphers'
    line: "Ciphers {{ ssh_preset.allowed_ciphers|join(',') }}"
    insertafter: *cipher_after
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Only allow reasonably secure MACs
  lineinfile:
    <<: *sshd_config_args
    regexp: '^#?MACs'
    line: "MACs {{ ssh_preset.allowed_macs|join(',') }}"
    insertafter: *cipher_after
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Only allow reasonably secure hostkey algorithms
  lineinfile:
    <<: *sshd_config_args
    regexp: '^#?HostKeyAlgorithms'
    line: "HostKeyAlgorithms {{ ssh_preset.allowed_hostkey_algos|join(',') }}"
    insertafter: *cipher_after
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Only allow reasonably secure publickey algorithms
  lineinfile:
    <<: *sshd_config_args
    regexp: '^#?PubkeyAcceptedKeyTypes'
    line: "PubkeyAcceptedKeyTypes {{ ssh_preset.allowed_pubkey_algos|join(',') }}"
    insertafter: *cipher_after
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']

- name: Set LogLevel to {{ ssh_loglevel }}
  lineinfile:
    <<: *sshd_config_args
    regexp: '^#?LogLevel'
    line: "LogLevel {{ ssh_loglevel }}"
  notify: reload sshd
  tags: ['prepare', 'prepare-sshd']
