---
# defaults file for sygnal

# General
sygnal_base_path: "/opt/sygnal"
sygnal_proc_name: "sygnal"
sygnal_version: "0.8.1"

# Apps
sygnal_apps: []

# Process
sygnal_pid_file: "{{ sygnal_base_path }}/sygnal.pid"
sygnal_supervision_method: docker
sygnal_deployment_method: docker

# HTTP
sygnal_listen_addresses: ['0.0.0.0']
sygnal_listen_port: 5000

# Logging
sygnal_log_level: "INFO"

# Database settings
sygnal_postgresql_database: "sygnal"
sygnal_postgresql_host: "localhost"
sygnal_postgresql_user: "sygnal"

# Container
sygnal_docker_name: sygnal
sygnal_docker_image: "matrixdotorg/sygnal:v{{ sygnal_version }}"
sygnal_docker_ports: []
sygnal_docker_labels_complete: "{{ sygnal_docker_labels_base | combine(sygnal_docker_labels) }}"
sygnal_docker_labels_base:
  version: "{{ sygnal_version }}"
sygnal_docker_labels: {}
