---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install gpg
      apt:
        state: present
        name:
          - gpg
          - dirmngr
      become: true
  roles:
    - role: element
