---

- name: Template wireguard config for interface {{ item.iface_name }}
  template:
    src: iface_config.conf.j2
    dest: "{{ wg_basedir }}/{{ item.iface_name }}.conf"
    mode: 0644
  register: wg_config_template

- name: Restart wg-quick@{{ item.iface_name }} systemd service if config changed
  systemd:
    name: wg-quick@{{ item.iface_name }}
    state: restarted
  when: wg_config_template.changed

- name: Enable systemd unit state for wg-quick@{{ item.iface_name }} and ensure it is started
  systemd:
    name: "wg-quick@{{ item.iface_name }}"
    state: "{{ item.systemd_unit_state | default('started') }}"
    enabled: "{{ item.systemd_unit_enabled | default('true') }}"
