---
language: python
services: docker

env:
  global:
    - ROLE_NAME: element
  matrix:
    - MOLECULE_DISTRO: debian9

install:
  - pip install molecule docker

jobs:
  include:
    - stage: default
      script: molecule test
