---
- import_tasks: install/void.yml
  when: ansible_os_family == "void"

- import_tasks: install/fedora.yml
  when: ansible_os_family == "RedHat"

- import_tasks: install/debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: install/arch.yml
  when: ansible_os_family == "Archlinux"

# TODO: Support more distros (and maybe even Windows one day)
