---
- name: Install python3
  hosts: [ all ]
  gather_facts: no
  tags: prepare
  pre_tasks:
    - name: test if python3 is present
      raw: test -e /usr/bin/python3
      register: python3_present
      check_mode: false
      changed_when: false
    - name: ensure python3 is installed
      raw: (apt -y update && apt install -y python3)
      when: python3_present.rc != 0

- name: Install packages
  hosts: [ all ]
  become: yes
  tags: prepare
  tasks:
    - name: Install basic packages
      apt:
        name:
          - acl
          - lsb-release
          - mtr
          - neovim
          - dnsutils  #dig
          - python3-setuptools
          - python3-ldap
          - python3-apt
          - python3-dev
          - python3-passlib
          - git
          - gcc
          - libffi-dev
          - tree
        cache_valid_time: 86400
      register: task_result
      until: task_result is success
      retries: 3
      delay: 2

- name: Install python dependencies
  hosts: [ all ]
  become: yes
  tags: [ 'prepare', 'prepare-python-libs' ]
  collections:
    - famedly.base
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
      - name: psycopg2-binary==2.8.6
      - name: matrix-nio>=0.17.0
  roles:
    - name: pip
