---
- name: Install and configure a matrix server
  hosts: [ all ]
  collections:
    - famedly.matrix
    - famedly.base
  become: yes
  roles:
    - role: postgresql_client_access
      vars:
        postgresql_client_access_users: "{{ matrix_synapse_postgresql_users }}"
        postgresql_client_access_databases: "{{ matrix_synapse_postgresql_databases }}"
        postgresql_client_access_hba_entries: "{{ matrix_synapse_postgresql_hba_entries }}"
    - role: synapse
      vars:
        matrix_synapse_docker_labels:
          traefik.enable: "true"
          traefik.http.routers.synapse.entrypoints: "web-secure"
          traefik.http.routers.synapse.rule: "Host(`matrix-{{ inventory_hostname }}`) && PathPrefix(`/_matrix/`, `/_synapse/`)"
          traefik.http.routers.synapse.tls.certresolver: "acme"
    - role: element
      vars:
        element_deployment_method: docker
        traefik_router_name: element
        traefik_service_name: element
        element_docker_labels:
          traefik.enable: "true"
          traefik.http.routers.element.entrypoints: "web-secure"
          traefik.http.routers.element.rule: "Host(`chat-{{ inventory_hostname }}`)"
          traefik.http.routers.element.tls.certresolver: "acme"
        element_domain_configs:
          - domain: "chat-{{ inventory_hostname }}"
            config:
              default_server_config:
                m.homeserver:
                  base_url: "https://matrix-{{ inventory_hostname }}"
                  server_name: "{{ inventory_hostname }}"
                m.identity_server:
                  base_url: "https://vector.im"
              disable_custom_urls: True
              disable_guests: True
              disable_login_language_selector: False
              disable_3pid_login: False
              brand: Element
              integrations_ui_url: "https://scalar.vector.im/"
              integrations_rest_url: "https://scalar.vector.im/api"
              integrations_widgets_urls:
                - "https://scalar.vector.im/_matrix/integrations/v1"
                - "https://scalar.vector.im/api"
                - "https://scalar-staging.vector.im/_matrix/integrations/v1"
                - "https://scalar-staging.vector.im/api"
                - "https://scalar-staging.riot.im/scalar/api"
              enable_presence_by_hs_url:
                "https://matrix.org": false
                "https://matrix-client.matrix.org": false
