- name: ensure sudo is installed
  package:
    name: sudo
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: ssh key loop
  include_tasks: user.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: sudoers template
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/{{ users_sudo_namespace }}"
    owner: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
  become: yes
